version: '3.8'

services:
  db:
    image: postgres
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    depends_on:
      - db
    build:
      context: ./
    restart: always
    env_file: ./.env
    ports:
      - ${API_PORT}:3000
    volumes:
      - ./:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}

volumes:
  db-data:
